# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Portfolio.Repo.insert!(%Portfolio.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Portfolio.Repo
alias Portfolio.Projects.Project

# add :name, :string
# add :class, :string
# add :semester, :string
# add :desc, :string
# add :imgs, {:array, :string}
# add :tags, {:array, :string}
# add :type, :integer
# add :isCS, :boolean
# add :link, :string
# ----> 1 graphic design, 2: coding, 3: UX/UI

# NEW SCHEMA
# add :type, :string
# add :name, :string
# add :link, :string
# add :semester, :string
# add :desc, :string
# add :imgs, {:array, :string}
# add :tags, {:array, :string}

# Graphic Type
# Date
# Time Spent
# Desc. 1 - n
# Tools Used
# Fun Rating

# NEW EDITIONS
p1 = Repo.insert!(%Project{type: "case", name: "Heatmaps and Stress Analysis for Digital Objects", link: "https://www.are.na/goreum-b/heatmaps-amp-stress-analysis", semester: "summer 2023", desc: "A response to the Are.na 2024 Editorial Prompt: Trace. An introduction into the exploration of applying the physical practices of stress analysis unto digital objects.", imgs: ["arena/heatmap.jpeg"], tags: ["are.na"]});
project23 = Repo.insert!(%Project{type: "project", isCS: false, link: "https://www.instagram.com/p/CLdNYx_BAkB/", name: "Personal Identity Exploration", semester: "spring 2021", desc: "A series of three self-promotional posters. I explored which traits are core to my identity, and what differentiates me from my peers. Intended to express my identity in a way that creates emotional resonance in a memorable, yet authentic manner. ", imgs: ["graphic/personal.png"], tags: ["Graphic Design", "Adobe Illustrator"]});
p4 = Repo.insert!(%Project{type: "case", name: "Work Portfolio V2 (v2.austinkim.works)", link: "http://v2.austinkim.works", semester: "spr 2023", desc: "Second version of my digital portfolio, holding more of my polished work more catered to the professional.", imgs: ["portfolio/v2.jpeg"], tags: ["Figma", "React", "Elixir"]});
p11 = Repo.insert!(%Project{type: "project", name: "The Lunchables Experience", link: "http://wwww.lunchablesexperience.com", semester: "june 11th 2023", desc: "A curated, multi-layered food experience based around the american-staple food product: Lunchables.", imgs: ["GD2/cover.png"], tags: ["Performance Art", "Experience Design"]});
project02 = Repo.insert!(%Project{type: "case", isCS: true, link: "https://junehomes.com/residences/new-york-city-ny/prospect-park-south/1688-prospect-park-south", name: "June Homes Apartment Page Redesign", semester: "winter 2022'", desc: "Large restructuring of June’s Apartment Page and booking system, two closely tied systems. June Home's Apartment Page was outdated, lacking in details about their reservation, and not tailored to reservation processes.", imgs: ["June/1_cover.jpg"], tags: ["Figma", "UX Design"]});
p33 = Repo.insert!(%Project{type: "photo", name: "textures & motifs 2", link: "https://www.instagram.com/p/Cs2JkgDtjq_/", semester: "may 2023", desc: "Collection of textures and motifs taken by a half-frame film camera. Edition 1.", imgs: ["photo/t&m2.jpeg"], tags: ["kycera"]});
p2 = Repo.insert!(%Project{type: "fabric", name: "Asymetrical Pleated Pant V1", link: "https://www.instagram.com/p/CsnJ5Y3M2st/", semester: "may 2023", desc: "First-pass at a tailored pair of pants. Inspired by asymmetrical skirt pants.", imgs: ["fabric/asym.JPG"], tags: [""]});
p45 = Repo.insert!(%Project{type: "audio", name: "[playlist] may 2023", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "may 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
project34 = Repo.insert!(%Project{type: "project", name: "Tamagotchi Model Rendering", link: "https://www.instagram.com/p/CU4Pc6hgamt/", semester: "fall 2021", desc: "Mocked up a tamagatchi model to practice my skills in Blender.", imgs: ["Lab/6_1.png", "Lab/6_1.png", "Lab/6_2.m4v", "Lab/6_3.png", "Lab/6_4.png"], tags: ["React.js", "Elixir-Phoenix"]});
project26 = Repo.insert!(%Project{type: "case", isCS: true, link: "", name: "PlayComb: A Covid-Friendly Playground", semester: "spring 2021", desc: "Socialization is a crucial aspect of childhood, as it cultivates creativity, emotion intelligence, and societal interactions. My senior design capstone team designed PlayComb to provide an exciting, refreshing and practical playground experience for kids of all ages through a modular layout focused on multiplicity, whist upholding social distancing.", imgs: ["Cap/cover.png"], tags: ["Web Design", "Blender", "Animation", "3D Print"]});
project04 = Repo.insert!(%Project{type: "case", isCS: true, link: "", name: "Ticketing System for Property Managers", semester: "spring 2023", desc: "June Homes works closely with House Keepers and Property Managers to clean and provide maintenance to all their homes. The tool they had used for years was an extension of an internal ticket-management system, June OS. This effort created a new app to better suit these workers.", imgs: ["June/3_cover.jpeg"], tags: ["Figma", "UX Design", "Material UI"]});
project283 = Repo.insert!(%Project{type: "project", isCS: false, link: "https://www.instagram.com/p/CK5V0LJhe9H/", name: "song poster design - Mac Miller: swimming", semester: "fall 2021", desc: "Part of a collection of graphics I've created for songs I've grown fond of over the years. Done for the late Mac Miller's album, Swimming.", imgs: ["Lab/4_1.png"], tags: ["Illustrator", "Photoshop"]});
project20 = Repo.insert!(%Project{type: "case", isCS: false, link: "", name: "YvStudio: Art Teacher Website Design", semester: "fall 2021", desc: "A free-lance project for a local high school art teacher, Yvette Kim. The website will be a showcase for her and her student's work, as well as being a 'sustainable' site for her to add and remove content directly on the website.", imgs: ["Freelance/1_1.jpeg"], tags: ["Figma", "Web Design", "Experience Design", "React.js"]});
p44 = Repo.insert!(%Project{type: "audio", name: "[playlist] april 2023", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "apr 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
project03 = Repo.insert!(%Project{type: "case", isCS: true, link: "", name: "Resident Application Redesign", semester: "summer 2022", desc: "To book any home with June, a user must first be approved through a Resident Application. This application verified a user’s identity, and would either approve or deny an application based on their financial information.", imgs: ["June/2_1.jpeg"], tags: ["Figma", "UX Design", "Automation"]});
project25 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "Orchestral Era Tokens", semester: "spring 2021", desc: "A series of posters advertising rare, collectible tokens connected to various orchestral music eras. Graphics for each poster were inspired the musical styles from each era. Baroque marks the beginning of light, modern structure in music compositions, Classical defines large, organized orchestral play for royalty and those in power, and Romantic defines compositions that were emotional, expressive, and humanistic.", imgs: ["IBD/3_5.png"], tags: ["Graphic Design", "Illustrator"]});
p43 = Repo.insert!(%Project{type: "audio", name: "[playlist] march 2023", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "mar 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
project17 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "88Rising Magazine Spread Design", semester: "spring 2019", desc: "A series of three magazine styles covering the rise in popularity around the media group: 88Rising. Featuring artists such as Rich Brain, Niki, and the Higher Brothers, I ventured into magazine/book designing for the first time in hopes of creating layouts that were engaging and reflect the energetic youth of these groups.", imgs: ["Type2/cover3.png", "Type2/3_0.jpg", "Type2/3_1.png", "Type2/3_2.jpg", "Type2/3_3.png", "Type2/3_4.png", "Type2/3_5.png", "Type2/3_6.png"], tags: ["InDesign", "Typography", "Illustrator"]});
project11 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "Narco-culture Infographic", semester: "fall 2018", desc: "An infographic briefly detailing the history of Narcoculture in Mexico, highlighting the presence and distribution of various drug cartels that took over Mexico from the 1980’s to present day (2020).", imgs: ["ID1/cover1.png", "ID1/1_0.png", "ID1/1_1.png", "ID1/1_2.png", "ID1/1_3.png"], tags: ["Illustrator", "Information Design"]});
p3 = Repo.insert!(%Project{type: "photo", name: "textures & motifs 1", link: "https://www.instagram.com/p/CrEUXCRut5L/", semester: "apr 2023", desc: "Collection of textures and motifs taken by a half-frame film camera. Edition 1.", imgs: ["photo/t&m1.jpeg"], tags: ["kycera"]});
project3 = Repo.insert!(%Project{type: "project", link: "", name: "Hard-Drive Paper Model", class_short: "3D", semester: "spring 2017", desc: "3D Hard Drive sketch and paper model for 3D", imgs: ["3D/cover2.png", "3D/2_1_T.png"], tags: ["Sketch-Up"]});
project10 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "International Holocaust Film Festival Conference", semester: "fall 2018", desc: "Developed a series of Stamps and Posters for the International Holocaust Film Festival. Inspired by, and using pictures taken from the Holocaust Museum in downtown Boston, the posters emphasized the importance of remembering those affected by the holocaust, the stamps highlighting the countries most directly affected by concentration camps. The stamps and logo for the poster were a result of a 100-iteration design practice.", imgs: ["GD1/cover.png"], tags: ["Illustrator", "Photography"]});
p42 = Repo.insert!(%Project{type: "audio", name: "[playlist] february 2023", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "feb 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
project284 = Repo.insert!(%Project{type: "project", isCS: false, link: "https://www.instagram.com/p/CURGRHKMQ6_/", name: "song poster design - Kendrick Lamar: Family Ties", semester: "fall 2022", desc: "Part of a collection of graphics I've created for songs I've grown fond of over the years. Series done for Kendrick Lamar and Baby Keem's song, Family Ties.", imgs: ["Lab/5_5.png"], tags: ["Illustrator", "Photoshop"]});
project24 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "Album Trading Cards", semester: "spring 2021", desc: "A series of three marketing posters advertising an Album Trading Card Product. Inspired by the resurgence of pokemon trading cards, the product consists of different sets of cards, based on music eras and genres. I would have liked to do more “limited edition” sets of these cards, and packaging designs, but for the assignment only explored a single set of posters.", imgs: ["IBD/cover2.png", "IBD/2_1.png", "IBD/2_2.png", "IBD/2_3.png", "IBD/2_4.png", "IBD/2_5.png", "IBD/2_6.png"], tags: ["Graphic Design", "Illustrator"]});
project2 = Repo.insert!(%Project{type: "project", link: "", name: "shoe storage project", class_short: "3D", semester: "spring 2017", desc: "Final project for a 3D Fundamentals class. Designed a functional storage piece to be used for travel.", imgs: ["3D/cover1.png", "3D/1_1_W.png", "3D/1_2_T.png", "3D/1_3_T.png", "3D/1_4_T.png", "3D/1_5_T.png"], tags: ["Design", "Sketch-Up"]});
p41 = Repo.insert!(%Project{type: "audio", name: "[playlist] january 2023", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "jan 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
p40 = Repo.insert!(%Project{type: "audio", name: "[playlist] december 2022", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "dec 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
project4 = Repo.insert!(%Project{type: "project", link: "", name: "Planet Beat-Looper", class_short: "PB", semester: "fall 2017", desc: "Final Project; Circular-based Beat Looper for Programming Baiscs", imgs: ["PB/1_1.png"], tags: ["P5.js"]});
project1 = Repo.insert!(%Project{type: "case", isCS: false, link: "", name: "portfolio design process V1", semester: "summer 2021", desc: "Documenting the process of how I built this portfolio. I further expanded on my front-end skills by working closely with React.js, Styled Components, and FramerAnimation to deliver an engaging experience to explore my previous works.", imgs: ["Website/cover.png", "Website/1_1.png", "Website/1_2.png", "Website/1_3.png", "Website/1_4.png", "Website/1_5.mp4",], tags: ["React.js", "Elixir-Phoenix", "Figma", "Experience Design"]});
p6 = Repo.insert!(%Project{type: "photo", name: "mini-series on homes from home", link: "https://www.instagram.com/p/CKH3qIEhSbH/", semester: "jan 2021", desc: "Mini-series on homes from my home. I've driven by these a thousand times, but never thought much of them. I was able to look at things differently this time around.", imgs: ["photo/houses1.jpeg"], tags: ["minolta srt-101"]});
project282 = Repo.insert!(%Project{type: "project", isCS: false, link: "https://www.instagram.com/p/B77nYyZhZb7/", name: "song poster design - Hundred Waters: Out Alee", semester: "fall 2020", desc: "Part of a collection of graphics I've created for songs I've grown fond of over the years. Done for Hundred Water's song, Out Alee.", imgs: ["Lab/3_1.png"], tags: ["Illustrator", "Photoshop"]});
p4 = Repo.insert!(%Project{type: "audio", name: "[playlist] november 2022", link: "https://open.spotify.com/playlist/6HjqVm9Ul9BSLiz6CRteTL?si=6325b871e0134ec9", semester: "nov 2023", desc: "Collection of Songs discovered in November that inspire, excite, or provoke emotion in me.", imgs: [""], tags: ["Spotify"]});
project6 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "Type Studies Exploration", semester: "spring 2018", desc: "A series of typography exploration exercises from a Typography 1 course. I explored analyzing and respecting the beauty of type by pinpointing and framing the various anatomy of type in one exercise, showcased a series of typefaces of my liking in another, and created a series of logos using only letterforms in another.", imgs: ["Type1/cover2.png", "Type1/2_0.jpg", "Type1/2_1.png", "Type1/2_2.jpg", "Type1/2_3.png", "Type1/2_4.jpg", "Type1/2_5.png", "Type1/2_6.png", "Type1/2_7.jpg"], tags: ["InDesign", "Typography"]});
project18 = Repo.insert!(%Project{type: "case", link: "", name: "Data Privacy Campaign", semester: "fall 2019", desc: "A Data Privacy Campaign is a project aimed at bringing awareness to data privacy, and the dangers surrounding it. Social media corporations are always watching, always collecting data on user’s habits. Final deliverable: website design mockup, series of Instagram Advertisements, series of posters, laptop and phone stickers, and business cards.", imgs: ["GD2/cover.png", "GD2/1_2.jpg", "GD2/1_3.jpg", "GD2/1_4.jpg", "GD2/1_10.jpg", "GD2/1_9.png", "GD2/1_6.png", "GD2/1_7.png", "GD2/1_8.png", "GD2/1_11.jpg", "GD2/1_12.jpg", "GD2/1_5.jpg"], tags: ["InDesign", "Illustrator", "Graphic Design"]});
project281 = Repo.insert!(%Project{type: "project", isCS: false, link: "", name: "song poster design - Raveena: Moonstone", semester: "fall 2020", desc: "Part of a collection of graphics I've created for songs I've grown fond of over the years. Done for Raveena's EP, Moonstone.", imgs: ["Lab/2_1.png"], tags: ["Illustrator", "Photoshop"]});
p5 = Repo.insert!(%Project{type: "audio", name: "Texas Instruments I", link: "https://www.soundcloud.com/nektine", semester: "TBD", desc: "Redacted", imgs: ["audio/TI1.png"], tags: ["Ableton Live 11"]});
project29 = Repo.insert!(%Project{type: "photo", name: "corners of ATL Suburbs", semester: "fall 2020", desc: "Small series of corners photographed around Atlanta.", imgs: ["Film/1_1.jpeg", "Film/1_2.jpeg", "Film/1_3.jpeg", "Film/1_4.jpeg", "Film/1_5.jpeg", "Film/1_6.jpeg"], tags: []});
project5 = Repo.insert!(%Project{type: "project", link: "", name: "Siddhartha Book Design", semester: "spring 2018", desc: "A book design typography exercise for the first chapter of Siddhartha: an Indian Tale by Hermann Hesse. Process involved printing and hand-binding (with tape) multiple sets of designs to further refine every page in this exercise.", imgs: ["Type1/cover1.png", "Type1/1_1_W.png", "Type1/1_2_T.png", "Type1/1_3_W.png"], tags: ["InDesign", "Typography"]});


# project8 = Repo.insert!(%Project{class: "5D", type: 1, isCS: false, link: "http://www.w3schools.com", name: "Fog X Flo", class_short: "5D", semester: "Fall '18", desc: "Fog X Flo project and reflection for 5D Fundamentals", imgs: ["5D/cover.png", "5D/1_1"], tags: ["Javascript", "CSS", "HTML", "Photography", "Experience Design"]});
# project27 = Repo.insert!(%Project{class: "Web Development", type: 2, isCS: false, link: "http://www.w3schools.com", name: "SpotifyParty", class_short: "WebDev", semester: "Spring '21", desc: "A platform for music enthusiasts to host music parties while also receiving party feedback from guests. A SpotifyParty connects to a host's spotify account, giving them playback control, as well as the ability to manage song requests/votings from all guests of their party. Attendees (or guests), have full view of the upcoming songs in the party, as well as the standings of their votes and requests sent to the party host. For every user signed up with SpotifyParty, their party song requests, voting habits, and songs played at any party they've been to, is displayed through a series of informative graphics, as well as an Impact score based on the user’s activeness.", imgs: ["WD/cover1.png", "WD/1_2.png", "WD/1_3.png", "WD/1_1.png", "WD/1_4.png", "WD/1_5.png", "WD/1_6.png", "WD/1_7.png"], tags: ["React.js", "Elixir-Phoenix", "Web Design", "Figma"]});
# project20 = Repo.insert!(%Project{class: "ID: Mobile", type: 3, isCS: false, link: "http://www.w3schools.com", name: "PhotoWalk", class_short: "ID:M", semester: "Fall '20", desc: "Photowalk is an app designed to encourage both digital and film photographers to become more familiar with their cities by going on “Photo Walks”, and expanding on their photography skills. By being able to share experiences through photos, walk routes, and specific stop locations, photographers can help others newer to the city to find interesting streets to take their own pictures of.", imgs: ["IDM/cover1.png", "IDM/0.png", "IDM/1_0.png", "Some early sketches and journey map.", "IDM/1_1.png", "IDM/1_2.png", "First set of prototypes.", "IDM/1_3.png", "Final Prototype.", "IDM/1_4.png", "IDM/1_5.png", "IDM/1_6.png"], tags: ["Figma", "Mobile Design", "Experience Design"]});
# project19 = Repo.insert!(%Project{class: "Software Development", type: 2, isCS: false, link: "http://www.w3schools.com", name: "Tsuro Game", class_short: "SD", semester: "Fall '19", desc: "Final Project; Tsuro Game for Software Development", imgs: ["SD/1_1.png"], tags: ["Java"]});
# project22 = Repo.insert!(%Project{class: "Human Computer Interaction", type: 3, isCS: false, link: "http://www.w3schools.com", name: "NEU Covid App Redesign", class_short: "HCI", semester: "Fall '20", desc: "An app redesign of the Northeastern Covid-Tracker app, focused on simplicity and functionality. Northeastern's required forms and flows are included, such as self-screening and positive test result forms, as well as a few features such as a news tab, extended account details on a user’s profile page, and a series of articles to encourage proper and safe Covid practices.", imgs: ["HCI/cover.png", "HCI/1_1.png", "HCI/1_1_WM.mov", "HCI/1_2_WM.mov"], tags: ["Figma", "Mobile Design"]});
# project12 = Repo.insert!(%Project{class: "ID1", type: 1, isCS: false, link: "http://www.w3schools.com", name: "Travel Guide", class_short: "ID1", semester: "Fall '18", desc: "An infographic book illustrating the details of traveling between my home-town (Atlanta), current location (Boston), and a city that I would like to travel to (Tokyo). Details included popular venues, attractions, and various pop-culture origins. Along the bottom of the entire book runs a distance map-line, marked with popular cities that you would pass on the way to each city.", imgs: ["ID1/cover2.png", "ID1/2_3_W.png", "ID1/2_4_W.png", "ID1/2_7.png", "ID1/2_6.png", "ID1/2_5.png", "ID1/2_1_W.png", "ID1/2_2_W.png"], tags: ["Illustrator", "InDesign", "Information Design"]});
# project13 = Repo.insert!(%Project{class: "ID1", type: 1, isCS: false, link: "http://www.w3schools.com", name: "How a Song is Built", class_short: "ID1", semester: "Fall '18", desc: "An infographic dissecting and explaining the anatomy of a song, in their most generic form. As complex a songs can be, I broke up what a very popular but standardized pop song from the 2000’s - 2020’s era would most likely entail, as well as the steps it takes for a song idea to develop into a produced song.", imgs: ["ID1/cover3.png", "ID1/3_1.png"], tags: ["Illustrator", "Information Design"]});
# project29 = Repo.insert!(%Project{class: "Web Development", type: 1, name: "Multiplayer Tsuro Game", class_short: "WebDev", semester: "Spring '21", desc: "Multiplayer Tsuro Game for Web Development", imgs: ["WD/3_1"], tags: ["React.js", "Elixir-Phoenix"]});
